### ISSUE TITLE
Crash while running the room finder skill

### ISSUE THREAD

**Issue by Xyaneon** [Xyaneon/LTUAssistantPlus#46]
See output below. The input is correctly recognized, but something is broken during the actual skill execution:
```
Google Speech Recognition thinks you said 'where is room s108'.
        verb:           (None)
        verb_object:    room
        alternate_noun: room
        adjective:      (None)
Traceback (most recent call last):
  File ".\LTUAssistant.py", line 45, in <module>
    process_command(services)
  File ".\LTUAssistant.py", line 25, in process_command
    if not skill_selection.identify_and_run_command(ud, services):
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\skill_selection.py", line 28, in identify_and_run_command
    skill.execute_for_command(skill_input, services)
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\skills\room_finder_skill.py", line 25, in execute_for_command
    verb_object = skill_input.noun
AttributeError: 'SkillInput' object has no attribute 'noun'
```

**Comment by Xyaneon** [comment]
I have a branch which will fix this and address other skill issues with improved testing using Python's `unittest.mock` package. CI testing on Windows is failing at the moment because of a Chocolatey service disruption (monitoring [here](https://status.chocolatey.org/)).
