### ISSUE TITLE
tell_schedule_skill.py IndexError crash

### ISSUE THREAD

**Issue by Xyaneon** [Xyaneon/LTUAssistantPlus#50]
See the below stacktrace which occurred (one event was stored at the time this was taken):
```
Hi Student! What can I help you with?
Say something!
Sending recorded speech to Google...
Google Speech Recognition thinks you said 'tell me my schedule'.
        verb:           tell
        verb_object:    schedule
        alternate_noun: schedule
        adjective:      (None)
test event, December 26 2019, 8 p.m.,

Traceback (most recent call last):
  File ".\LTUAssistant.py", line 45, in <module>
    process_command(services)
  File ".\LTUAssistant.py", line 25, in process_command
    if not skill_selection.identify_and_run_command(ud, services):
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\skill_selection.py", line 28, in identify_and_run_command
    skill.execute_for_command(skill_input, services)
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\skills\tell_schedule_skill.py", line 27, in execute_for_command
    event_list = services.calendar_service.get_todays_events()
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\services\calendar\calendar_service.py", line 48, in get_todays_events
    event_list = self.read_events()
  File "C:\Users\chris\source\repos\Xyaneon\LTUAssistantPlus\LTUAssistantPlus\services\calendar\calendar_service.py", line 33, in read_events
    event_list.append(CalendarEvent(row[0], row[1], row[2], row[3]))
IndexError: list index out of range
```

**Comment by Xyaneon** [comment]
This occurred because there was no end time to read, which the method expected. End times for events are not requested by `AddCalendarEventSkill`.
